ENEMY_WALK:
	PRINT_DYN_IMG(tijolo,ENEMY_POSX,ENEMY_POSY)
	SWITCH_FRAME()
	PRINT_DYN_IMG(tijolo,ENEMY_POSX,ENEMY_POSY)
	SWITCH_FRAME()
	LOADW(a1,ENEMY_POSX)
	LOADW(a2,ENEMY_POSY)
	LOADW(a3,ENEMY_SPEED)
	add a1,a1,a3
	CALCULATE_BLOCK(a1,a2)
	LOADW(t2,ENEMY_FINAL_BLOCK)
	bne t1,t2,EW_KEEP
	li t2,-16
	SAVEW(t2,ENEMY_SPEED)
	j EW_WALK
EW_KEEP:
	LOADW(t2,ENEMY_INITIAL_BLOCK)
	bne t1,t2,EW_WALK
	li t2,16
	SAVEW(t2,ENEMY_SPEED)
EW_WALK:
	LOADW(a1,ENEMY_POSX)
	LOADW(a2,ENEMY_POSY)
	LOADW(a3,ENEMY_SPEED)
	add a1,a1,a3
	SAVEW(a1,ENEMY_POSX)
	jal COLISION_TEST
	PRINT_DYN_IMG(enemy,ENEMY_POSX,ENEMY_POSY)
	SWITCH_FRAME()
	PRINT_DYN_IMG(enemy,ENEMY_POSX,ENEMY_POSY)
	SWITCH_FRAME()
	j POLL_LOOP
